### ISSUE TITLE
Replace _rootSub With A Callback

### ISSUE THREAD

**Issue by dOrgJelli** [graphprotocol/mutations#6]
Investigate if we can replace _rootSub with a simple callback function.

**Comment by dOrgJelli** [comment]
If we did this, the implementation would become less straight forward, as we would have to create a strange pattern to effectively wrap our `setState` callbacks with subjects so we can subscribe to all of them at once for aggregate state update purposes:
https://github.com/graphprotocol/mutations/blob/6752681679ff5b44fcba02b8bafa8c9bf32db3cc/packages/mutations/src/index.ts#L94-L103

**Comment by Jannis** [comment]
Agreed, I don't think there is a need to replace `rootSubject` with something that's not an observable.
